project:
  type: book

book:
  title: "ds_book"
  author: "Igor Veksler"
  date: "12/4/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - linear_algebra.qmd
    - optimization.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



