# Introduction & Motivations

I have always been interested in how can somebody make a meaningful contribution to Aritifical Intelligence without a formal education or a phd. ("playa hatin degree") This spans the spectrum of being a practitioner in industry to making theoretical advancements via a paper. I originally wrote about this topic in the 2018 post [Bootstrapping a Modern Data Science Education](https://www.datarobot.com/blog/booststrapping-a-modern-datascience-education/) while at DataRobot. My views have updated and this provides deeper content along this path. This repository will contain longer form content from the [ds_skills repository](https://github.com/iveksl2/ds_skills) 

The book [Introduction to Probability for Data Science by Stnaley H. Chan](https://probability4datascience.com/) provides a glimpse into the future of publishing technical content. This contains longer form text explanations as well as code samples and video lectures. This provides all the modalities of learning on behalf of the student.

We are on the precepice of a golden age of education as now so much of the worlds content from the leading minds is readily accessible to anyone for free. 

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">We live in an AWESOME age of enlightenment. <br><br>Oh, you wanna learn about SVD? Have <a href="https://twitter.com/luis_likes_math?ref_src=twsrc%5Etfw">@luis_likes_math</a> break it down for you[1]. Or have <a href="https://twitter.com/3blue1brown?ref_src=twsrc%5Etfw">@3blue1brown</a> show you how to bend space with your mind (&amp; linear algebra) [2]. Or just attend the whole MIT course [3].<br><br>We&#39;re incredibly blessed.</p>&mdash; Jay Alammar (@JayAlammar) <a href="https://twitter.com/JayAlammar/status/1357704242371395585?ref_src=twsrc%5Etfw">February 5, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>